### ISSUE TITLE
babel-plugin-transform-npm 这个依赖在NPM上根本就找不到。。。。

### ISSUE THREAD

**Issue by singcl** [cwsjoker/Cnode-vue-spa#1]
babel-plugin-transform-npm 这个依赖在NPM上根本就找不到。。。。

**Comment by cwsjoker** [comment]
可以试试cnpm，有可能是npm卡主了，载不出来。

**Comment by tomorrow01** [comment]
babel-plugin-transform-npm这个安装不了，不安装可以吗？

**Comment by cwsjoker** [comment]
额，这个不安装可能有些es6的api用不了。蛮用吧，遇到问题在说咯。

**Comment by tomorrow01** [comment]
不安装babel-plugin-transform-npm，项目编译成功了，打开index.html总是报错。
报错如下：
 common.js:80 GET file:///D:/build/1.build.js?87dde524ad030120a756 net::ERR_FILE_NOT_FOUND

**Comment by tomorrow01** [comment]
新手学习，多多指教

**Comment by cwsjoker** [comment]
你把项目重装一下，用cnpm把依赖载进来

**Comment by tomorrow01** [comment]
我去试试。

**Comment by tomorrow01** [comment]
用cnpm 也安装不上呢。报错如下：

D:\webpackdemo2>cnpm install babel-plugin-transform-npm
Error: GET https://registry.npm.taobao.org/babel-plugin-transform-npm/latest res
ponse 404 status
    at get (C:\Users\MyPC\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm
install\lib\get.js:45:17)
    at next (native)
    at onFulfilled (C:\Users\MyPC\AppData\Roaming\npm\node_modules\cnpm\node_mod
ules\npminstall\node_modules\co\index.js:65:19)
    at process._tickCallback (node.js:369:9)
npminstall version: 2.4.1
npminstall args: D:\soft_anzhuang\nodejs\node.exe C:\Users\MyPC\AppData\Roaming\
npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --china --userconfi
g=C:\Users\MyPC.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry
=https://registry.npm.taobao.org babel-plugin-transform-npm

**Comment by cwsjoker** [comment]
这个是只安装了bable，一起安装下来的

**Comment by jfmuser** [comment]
这个包babel-plugin-transform-npm怎么都下不下来，用npm和cnpm都试过，要不楼主把依赖的包也传一下？

**Comment by cwsjoker** [comment]
谁要加下我QQ419436210我传给他，不传github

**Comment by cwsjoker** [comment]
bable是整套安装进来，我下载的依赖包也没有bable-plugin-transform-npm好像是叫bable-plugin-transform-runtime，程序是没有问题的。

**Comment by zengweiyikuyi** [comment]
babel的改了一下就可以安装了

"babel-core": "^6.1.2",
    "babel-loader": "^6.1.0",
    "babel-plugin-transform-runtime": "^6.1.2",
    "babel-preset-es2015": "^6.1.2",
    "babel-runtime": "^5.8.0",

**Comment by cwsjoker** [comment]
项目依赖改过来了，现在安装可以运行了。
