### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined(…)

### ISSUE THREAD

**Issue by fanyongfeng** [cwsjoker/Cnode-vue-spa#3]
Uncaught TypeError: Cannot read property 'call' of undefined(…)
我每次构建run项目都会抛出这个错误，请问一下这是什么原因呢

**Comment by cwsjoker** [comment]
run dev or run build？

**Comment by fanyongfeng** [comment]
run dev

**Comment by fanyongfeng** [comment]
我把entry  改为 './src/main.js' 之后就是可以的了， 我google 了 很久也没有明白是什么问题

**Comment by fanyongfeng** [comment]
npm配置里面  没有 path

**Comment by cwsjoker** [comment]
好吧，依赖没载全

**Comment by fanyongfeng** [comment]
谢谢
